### ISSUE TITLE
small change needed to get it working with Edge

### ISSUE THREAD

**Issue by ossandust** [sensaura-public/iotweb#1]
First of all thanks for this very interesting project ! 
Currently the UWP projects don't compile - probably work in progress - the fixes are obvious (move the port specification from Start() to ctor and a few other minor changes to comply to the IServer interface.
More importantly, I noticed that web sockets don't work from Edge. Apparently the check on the header values in UpgradeToWebsocket() must be made case insensitive - the Edge browser sends a header "Upgrade:Websocket" which doesn't get recognized. See the official spec at https://tools.ietf.org/html/rfc6455#section-4.2.1 > section 4.2.1.3 & 4.2.1.4
Thanks!

**Comment by sensaura-public** [comment]
Thanks, I've queued it for the next release. The 0.8.x branch is more stable (that is the code that is used to generate the NuGet package). The master branch may or may not work at any given time.

**Comment by sensaura-public** [comment]
Fixed in branches 0.8.x and master - will be rolled into next NuGet version.
