### ISSUE TITLE
small change needed to get it working on port 80

### ISSUE THREAD

**Issue by ossandust** [sensaura-public/iotweb#2]
Really a very small typo, but I thought I'd mention it because it can take some time to find out...
In the demo file index.html, when wsURL is created, a space is inserted instead of a portnumber when using port 80. Should be an empty string instead:
var wsURL = "ws://" + location.hostname + (location.port ? ':' + location.port : '') + "/sockets/";

**Comment by sensaura-public** [comment]
Thanks, I'll make the change. Listening on port 80 is restricted on UWP so most of the testing has been done with non-standard ports.

**Comment by sensaura-public** [comment]
Fixed in branches 0.8.x and master - will be rolled into next NuGet version.
